version: 2.1

commands:
  build-and-test:
    description: general build steps
    steps:
    - checkout
    - run:
        name: npm install
        command: cd awe/resources/client/awe && npm install
    - run:
        command: virtualenv build-env
    - run:
        name: install package in build env
        command: source build-env/bin/activate && pip install -e .
    - run:
        name: make build
        command: source build-env/bin/activate && make build
    - run:
        command: virtualenv test-env
    - run:
        name: pip install dist
        command: source test-env/bin/activate && pip install dist/*
    - run:
        name: install test requirements
        command: source test-env/bin/activate && pip install -r requirements/test-requirements.txt
    - run:
        name: make test
        command: source test-env/bin/activate && make test
    - run:
        name: check isolated dist package
        command: source test-env/bin/activate && cd test-env && python -c 'import awe; awe.Page()'

  artifacts:
    description: collect actifacts
    steps:
    - store_artifacts:
        path: test-reports
    - store_test_results:
        path: test-reports

jobs:
  build:
    docker:
    - image: circleci/python:2.7-stretch-node-browsers
    steps:
    - build-and-test
    - artifacts
  build37:
    docker:
    - image: circleci/python:3.7-stretch-node-browsers
    steps:
    - build-and-test
    - run:
        name: make pytest3
        command: source test-env/bin/activate && make pytest3
    - artifacts

workflows:
  version: 2
  workflow:
    jobs:
    - build
    - build37
